version: "3.8"
services:
  gorc:
    image: aiax-gorc
    command: orchestrator start --cosmos-key=orchestrator --ethereum-key=signer
    volumes:
      - ./data/gorc:/aiax/data/gorc
    restart: on-failure

  aiaxd:
    image: aiax-aiaxd
    command: start
    volumes:
      - ./data/aiaxd:/aiax/data/aiaxd
    restart: on-failure

  eth:
    image: ethereum/client-go:stable
    command: --goerli --http --http.addr=0.0.0.0 --http.vhosts=* --syncmode light
    volumes:
      - ./data/eth:/root/.ethereum
    restart: on-failure